# Make sure this file has unix line endings as otherwise Renovate breaks
# Some definitions are also used in generating the IPC interfaces.

[versions]
antver = "1.10.15"
antlr4ver = "4.13.1"
aopalliancever = "1.0"
aspectjver = "1.9.7"
axiomver = "1.2.21"
axis2ver = "1.7.9"
axis2meximplver = "1.3"
checkerqualver = "3.49.5"
checkstylever = "10.12.2"
commonsbeanutilsver = "1.11.0"
commonscliver = "1.10.0"
commonscodecver = "1.17.0"
commonscollectionsver = "3.2.2"
commonscollections4ver = "4.5.0"
commonsconfiguration2ver = "2.12.0"
commonsdigester3ver = "3.2"
commonsfileuploadver = "1.6.0"
commonsiover = "2.20.0"
commonslang3ver = "3.18.0"
commonsloggingver = "1.3.5"
commonsnetver = "3.12.0"
commonstransactionver = "1.2"
commonstextver = "1.12.0"
commonsvalidatorver = "1.10.0"
esapiver = "2.7.0.0"
geronimoannotationspecver = "1.1.1"
geronimojaxwsspecver = "1.2"
geronimojtaspecver = "1.1.1"
geronimosaajspecver = "1.1"
geronimostaxapispecver = "1.0.1"
geronimowsmetadataspecver = "1.1.3"
glassfishver = "4.0.0-M1"
gsonver = "2.13.1"
guavaver = "33.3.1-jre"
guicever = "5.1.0"
gwtver = "2.11.0"
gwtwebworkerver = "1.0.9"
htmlunitver = "4.4.0"
httpclientver = "4.5.14"
httpcorever = "4.4.16"
icu4jver = "75.1"
jacocover = "0.8.13"
jakartamailapiver = "2.1.2"
jakartaxmlbindapi2ver = "2.3.3"
jakartaxmlbindapi3ver = "3.0.1"
jalopyver = "1.5rc3"
javassistver = "3.30.2-GA"
javaxinjectver = "1"
javaxmailapiver = "1.6.2"
javaxservletapiver = "4.0.1"
javaxtransactionapiver = "1.2"
javaxwebsocketapiver = "1.1"
jaxbapiver = "2.3.1"
jaxbver = "2.3.9"
jaxbxewpluginver = "2.1"
jaxenver = "2.0.0"
jaxwstoolsver = "4.0.2"
jcommanderver = "1.82"
jdom2ver = "2.0.6.1"
jettisonver = "1.5.4"
jettyver = "12.0.13"
jettywebver = "11.0.24"
jibxbindver = "1.4.2"
jibxrunver = "1.4.2"
jnaver = "5.17.0"
jsr311apiver = "1.1.1"
jstlapiver = "1.2"
junitjupiterver = "5.10.2"
junitparamsver = "1.1.1"
log4jver = "2.25.1"
miglayoutver = "3.7.4"
mockitover = "1.10.19"
neethiver = "3.2.1"
powermock1ver = "1.7.4"
powermock2ver = "2.0.9"
regexpver = "1.3"
relaxngver = "4.0.0-M1"
saxonver = "9.1.0.8"
strutsver = "1.2.4"
strutselver = "1.3.10"
taglibsver = "1.1.2"
taglibsimplver = "1.2.5"
testngver = "7.10.2"
tomcatver = "9.0.110"
urlrewritefilterver = "4.0.4"
wodenver = "1.0M10"
woodstoxcorever = "7.0.0"
wsdl4jver = "1.6.3"
xalanver = "2.7.3"
xmlapisver = "1.4.01"
xmlapisextver = "1.3.04"
xmlbeansver = "5.3.0"
xmlresolverver = "1.2"
xmlschemacorever = "2.3.1"



[libraries]
ant = { group = "org.apache.ant", name = "ant", version.ref = "antver" }
antjunit = { group = "org.apache.ant", name = "ant-junit", version.ref = "antver" }

antlr4runtime = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr4ver" }

aopalliance = { group = "aopalliance", name = "aopalliance", version.ref = "aopalliancever" }

aspectjrt = { group = "org.aspectj", name = "aspectjrt", version.ref = "aspectjver" }
aspectjtools = { group = "org.aspectj", name = "aspectjtools", version.ref = "aspectjver" }

axiomapi = { group = "org.apache.ws.commons.axiom", name = "axiom-api", version.ref = "axiomver" }
axiomdom = { group = "org.apache.ws.commons.axiom", name = "axiom-dom", version.ref = "axiomver" }
axiomimpl = { group = "org.apache.ws.commons.axiom", name = "axiom-impl", version.ref = "axiomver" }

axis2adb = { group = "org.apache.axis2", name = "axis2-adb", version.ref = "axis2ver" }
axis2adbcodegen = { group = "org.apache.axis2", name = "axis2-adb-codegen", version.ref = "axis2ver" }
axis2antplugin = { group = "org.apache.axis2", name = "axis2-ant-plugin", version.ref = "axis2ver" }
axis2clustering = { group = "org.apache.axis2", name = "axis2-clustering", version.ref = "axis2ver" }
axis2codegen = { group = "org.apache.axis2", name = "axis2-codegen", version.ref = "axis2ver" }
axis2corba = { group = "org.apache.axis2", name = "axis2-corba", version.ref = "axis2ver" }
axis2fastinfoset = { group = "org.apache.axis2", name = "axis2-fastinfoset", version.ref = "axis2ver" }
axis2java2wsdl = { group = "org.apache.axis2", name = "axis2-java2wsdl", version.ref = "axis2ver" }
axis2jaxbri = { group = "org.apache.axis2", name = "axis2-jaxbri", version.ref = "axis2ver" }
axis2jaxws = { group = "org.apache.axis2", name = "axis2-jaxws", version.ref = "axis2ver" }
axis2jibx = { group = "org.apache.axis2", name = "axis2-jibx", version.ref = "axis2ver" }
axis2json = { group = "org.apache.axis2", name = "axis2-json", version.ref = "axis2ver" }
axis2kernel = { group = "org.apache.axis2", name = "axis2-kernel", version.ref = "axis2ver" }
axis2metadata = { group = "org.apache.axis2", name = "axis2-metadata", version.ref = "axis2ver" }
axis2mtompolicy = { group = "org.apache.axis2", name = "axis2-mtompolicy", version.ref = "axis2ver" }
axis2saaj = { group = "org.apache.axis2", name = "axis2-saaj", version.ref = "axis2ver" }
axis2soapmonitorservlet = { group = "org.apache.axis2", name = "axis2-soapmonitor-servlet", version.ref = "axis2ver" }
axis2spring = { group = "org.apache.axis2", name = "axis2-spring", version.ref = "axis2ver" }
axis2transporthttp = { group = "org.apache.axis2", name = "axis2-transport-http", version.ref = "axis2ver" }
axis2transportlocal = { group = "org.apache.axis2", name = "axis2-transport-local", version.ref = "axis2ver" }
axis2xmlbeans = { group = "org.apache.axis2", name = "axis2-xmlbeans", version.ref = "axis2ver" }
axis2meximpl = { group = "org.apache.axis2", name = "mex-impl", version.ref = "axis2meximplver" }

checkerqual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerqualver" }

checkstyle = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "checkstylever" }

commonsbeanutils = { group = "commons-beanutils", name = "commons-beanutils", version.ref = "commonsbeanutilsver" }

commonscli = { group = "commons-cli", name = "commons-cli", version.ref = "commonscliver" }

commonscodec = { group = "commons-codec", name = "commons-codec", version.ref = "commonscodecver" }

commonscollections = { group = "org.apache.commons", name = "commons-collections", version.ref = "commonscollectionsver" }

commonscollections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commonscollections4ver" }

commonsconfiguration2 = { group = "org.apache.commons", name = "commons-configuration2", version.ref = "commonsconfiguration2ver" }

commonsdigester3 = { group = "org.apache.commons", name = "commons-digester3", version.ref = "commonsdigester3ver" }

commonsfileupload = { group = "commons-fileupload", name = "commons-fileupload", version.ref = "commonsfileuploadver" }

commonsio = { group = "commons-io", name = "commons-io", version.ref = "commonsiover" }

commonslang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonslang3ver" }

commonslogging = { group = "commons-logging", name = "commons-logging", version.ref = "commonsloggingver" }

commonsnet = { group = "commons-net", name = "commons-net", version.ref = "commonsnetver" }

commonstext = { group = "org.apache.commons", name = "commons-text", version.ref = "commonstextver" }

commonstransaction = { group = "commons-transaction", name = "commons-transaction", version.ref = "commonstransactionver" }

commonsvalidator = { group = "commons-validator", name = "commons-validator", version.ref = "commonsvalidatorver" }

esapi = { group = "org.owasp.esapi", name = "esapi", version.ref = "esapiver" }

geronimoannotationspec = { group = "org.apache.geronimo.specs", name = "geronimo-annotation_1.0_spec", version.ref = "geronimoannotationspecver" }
geronimojaxwsspec = { group = "org.apache.geronimo.specs", name = "geronimo-jaxws_2.2_spec", version.ref = "geronimojaxwsspecver" }
geronimojtaspec = { group = "org.apache.geronimo.specs", name = "geronimo-jta_1.1_spec", version.ref = "geronimojtaspecver" }
geronimosaajspec = { group = "org.apache.geronimo.specs", name = "geronimo-saaj_1.3_spec", version.ref = "geronimosaajspecver" }
geronimostaxapispec = { group = "org.apache.geronimo.specs", name = "geronimo-stax-api_1.0_spec", version.ref = "geronimostaxapispecver" }
geronimowsmetadataspec = { group = "org.apache.geronimo.specs", name = "geronimo-ws-metadata_2.0_spec", version.ref = "geronimowsmetadataspecver" }

glassfishcodemodel = { group = "org.glassfish.jaxb", name = "codemodel", version.ref = "glassfishver" }
glassfishtxw2 = { group = "org.glassfish.jaxb", name = "txw2", version.ref = "glassfishver" }
glassfishxsom = { group = "org.glassfish.jaxb", name = "xsom", version.ref = "glassfishver" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonver" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guavaver" }

guice = { group = "com.google.inject", name = "guice", version.ref = "guicever" }
guiceassistedinject = { group = "com.google.inject.extensions", name = "guice-assistedinject", version.ref = "guicever" }

gwtdev = { group = "org.gwtproject", name = "gwt-dev", version.ref = "gwtver" }
gwtservlet = { group = "org.gwtproject", name = "gwt-servlet", version.ref = "gwtver" }
gwtuser = { group = "org.gwtproject", name = "gwt-user", version.ref = "gwtver" }
gwtwebworker = { group = "de.knightsoft-net", name = "gwt-webworker", version.ref = "gwtwebworkerver" }

htmlunit = { group = "org.htmlunit", name = "htmlunit", version.ref = "htmlunitver" }
nekohtmlunit = { group = "org.htmlunit", name = "neko-htmlunit", version.ref = "htmlunitver" }
httpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclientver" }
httpcore = { group = "org.apache.httpcomponents", name = "httpcore", version.ref = "httpcorever" }

icu4j = { group = "com.ibm.icu", name = "icu4j", version.ref = "icu4jver" }

jacocoagent = { group = "org.jacoco", name = "org.jacoco.agent", version.ref = "jacocover" }
jacocoant = { group = "org.jacoco", name = "org.jacoco.ant", version.ref = "jacocover" }

jalopy = { group = "jalopy", name = "jalopy", version.ref = "jalopyver" }

jakartamailapi = { group = "jakarta.mail", name = "jakarta.mail-api", version.ref = "jakartamailapiver" }

jakartaxmlbindapi2 = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakartaxmlbindapi2ver" }
jakartaxmlbindapi3 = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakartaxmlbindapi3ver" }

javassist = { group = "org.javassist", name = "javassist", version.ref = "javassistver" }

javaxinject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxinjectver" }
javaxmailapi = { group = "javax.mail", name = "javax.mail-api", version.ref = "javaxmailapiver" }

javaxservletapi = { group = "javax.servlet", name = "javax.servlet-api", version.ref = "javaxservletapiver" }

javaxtransactionapi = { group = "javax.transaction", name = "javax.transaction-api", version.ref = "javaxtransactionapiver" }

javaxwebsocketapi = { group = "javax.websocket", name = "javax.websocket-api", version.ref = "javaxwebsocketapiver" }

jaxbimpl = { group = "com.sun.xml.bind", name = "jaxb-impl", version.ref = "jaxbver" }
jaxbxjc = { group = "com.sun.xml.bind", name = "jaxb-xjc", version.ref = "jaxbver" }
jaxbxewplugin = { group = "com.github.jaxb-xew-plugin", name = "jaxb-xew-plugin", version.ref = "jaxbxewpluginver" }

jaxbapi = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxbapiver" }
jaxen = { group = "jaxen", name = "jaxen", version.ref = "jaxenver" }
jaxwstools = { group = "com.sun.xml.ws", name = "jaxws-tools", version.ref = "jaxwstoolsver" }

jcommander = { group = "com.beust", name="jcommander", version.ref = "jcommanderver" }

jdom2 = { group = "org.jdom", name = "jdom2", version.ref = "jdom2ver" }

jettison = { group = "org.codehaus.jettison", name = "jettison", version.ref = "jettisonver" }

jettyhttp = { group = "org.eclipse.jetty", name = "jetty-http", version.ref = "jettyver" }
jettysecurity = { group = "org.eclipse.jetty", name = "jetty-security", version.ref = "jettyver" }
jettyserver = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jettyver" }
jettyservlet = { group = "org.eclipse.jetty", name = "jetty-servlet", version.ref = "jettywebver" }
jettyservlets = { group = "org.eclipse.jetty", name = "jetty-servlets", version.ref = "jettywebver" }
jettywebapp = { group = "org.eclipse.jetty", name = "jetty-webapp", version.ref = "jettywebver" }
jettyxml = { group = "org.eclipse.jetty", name = "jetty-xml", version.ref = "jettyver" }

jibxbind = { group = "org.jibx", name = "jibx-bind", version.ref = "jibxbindver" }
jibxrun = { group = "org.jibx", name = "jibx-run", version.ref = "jibxrunver" }

jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jnaver" }
jnaplatform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jnaver" }

jsr311api = { group = "javax.ws.rs", name = "jsr311-api", version.ref = "jsr311apiver" }

jstlapi = { group = "javax.servlet.jsp.jstl", name = "jstl-api", version.ref = "jstlapiver" }

junitjupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitjupiterver" }

junitparams = { group = "pl.pragmatists", name = "JUnitParams", version.ref = "junitparamsver" }

log4j12api = { group = "org.apache.logging.log4j", name = "log4j-1.2-api", version.ref = "log4jver" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4jver" }
log4jappserver = { group = "org.apache.logging.log4j", name = "log4j-appserver", version.ref = "log4jver" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4jver" } # Also used in generation of java3 IPC interfaces.
log4jjcl = { group = "org.apache.logging.log4j", name = "log4j-jcl", version.ref = "log4jver" }
log4jslf4j2impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4jver" } # Also used in generation of java3 IPC interfaces.

mockitoall = { group = "org.mockito", name = "mockito-all", version.ref = "mockitover" } # Also used in generation of java3 IPC interfaces.

miglayout = { group = "com.miglayout", name = "miglayout", version.ref = "miglayoutver" }

neethi = { group = "org.apache.neethi", name = "neethi", version.ref = "neethiver" }

powermock = { group = "org.powermock", name = "powermock", version.ref = "powermock1ver" }
powermockapimockito = { group = "org.powermock", name = "powermock-api-mockito", version.ref = "powermock1ver" }
powermockapimockitocommon = { group = "org.powermock", name = "powermock-api-mockito-common", version.ref = "powermock1ver" }
powermockapimockito2 = { group = "org.powermock", name = "powermock-api-mockito2", version.ref = "powermock2ver" }
powermockapisupport = { group = "org.powermock", name = "powermock-api-support", version.ref = "powermock1ver" }
powermockclassloadingbase = { group = "org.powermock", name = "powermock-classloading-base", version.ref = "powermock1ver" }
powermockcore = { group = "org.powermock", name = "powermock-core:", version.ref = "powermock2ver" }
powermockmodulejunit3 = { group = "org.powermock", name = "powermock-module-junit3", version.ref = "powermock1ver" }
powermockmodulejunit4 = { group = "org.powermock", name = "powermock-module-junit4", version.ref = "powermock1ver" }
powermockmodulejunit4common = { group = "org.powermock", name = "powermock-module-junit4-common", version.ref = "powermock1ver" }
powermockmodulejunit4legacy = { group = "org.powermock", name = "powermock-module-junit4-legacy", version.ref = "powermock1ver" }
powermockmoduletestng = { group = "org.powermock", name = "powermock-module-testng", version.ref = "powermock1ver" }
powermockmoduletestngcommon = { group = "org.powermock", name = "powermock-module-testng-common", version.ref = "powermock2ver" }
powermockreflect = { group = "org.powermock", name = "powermock-reflect", version.ref = "powermock2ver" }

regexp = { group = "regexp", name = "regexp", version.ref = "regexpver" }

rngom = { group = "com.sun.xml.bind.external", name = "rngom", version.ref = "relaxngver" }
relaxngdatatype = { group = "com.sun.xml.bind.external", name = "relaxng-datatype", version.ref = "relaxngver" }

saxon = { group = "net.sourceforge.saxon", name = "saxon", version.ref = "saxonver" }

struts = { group = "struts", name = "struts", version.ref = "strutsver" }

strutsel = { group = "org.apache.struts", name = "struts-el", version.ref = "strutselver" }

taglibs = { group = "taglibs", name = "standard", version.ref = "taglibsver" }
taglibsimpl = { group = "org.apache.taglibs", name = "taglibs-standard-impl", version.ref = "taglibsimplver" }

testng = {group = "org.testng", name = "testng", version.ref = "testngver" }

tomcatapi = { group = "org.apache.tomcat", name = "tomcat-api", version.ref = "tomcatver" }
tomcatcatalina = { group = "org.apache.tomcat", name = "tomcat-catalina", version.ref = "tomcatver" }
tomcatcoyote = { group = "org.apache.tomcat", name = "tomcat-coyote", version.ref = "tomcatver" }
tomcatelapi = { group = "org.apache.tomcat", name = "tomcat-el-api", version.ref = "tomcatver" }
tomcatjasper = { group = "org.apache.tomcat", name = "tomcat-jasper", version.ref = "tomcatver" }
tomcatjasperel = { group = "org.apache.tomcat", name = "tomcat-jasper-el", version.ref = "tomcatver" }
tomcatjspapi = { group = "org.apache.tomcat", name = "tomcat-jsp-api", version.ref = "tomcatver" }
tomcatjuli = { group = "org.apache.tomcat", name = "tomcat-juli", version.ref = "tomcatver" }
tomcatservletapi = { group = "org.apache.tomcat", name = "tomcat-servlet-api", version.ref = "tomcatver" }
tomcattribes = { group = "org.apache.tomcat", name = "tomcat-tribes", version.ref = "tomcatver" }
tomcatutil = { group = "org.apache.tomcat", name = "tomcat-util", version.ref = "tomcatver" }
tomcatutilscan = { group = "org.apache.tomcat", name = "tomcat-util-scan", version.ref = "tomcatver" }
tomcatwebsocket = { group = "org.apache.tomcat", name = "tomcat-websocket", version.ref = "tomcatver" }
tomcatwebsocketapi = { group = "org.apache.tomcat", name = "tomcat-websocket-api", version.ref = "tomcatver" }

urlrewritefilter = { group = "org.tuckey", name = "urlrewritefilter", version.ref = "urlrewritefilterver" }

woden = { group = "org.apache.woden", name = "woden", version.ref = "wodenver" }
wsdl4j = { group = "wsdl4j", name = "wsdl4j", version.ref = "wsdl4jver" }
woodstoxcore = { group = "com.fasterxml.woodstox", name = "woodstox-core", version.ref = "woodstoxcorever" }

xalan = { group = "xalan", name = "xalan", version.ref = "xalanver" }
xalanserializer = { group = "xalan", name = "serializer", version.ref = "xalanver" }

xmlapis = { group = "xml-apis", name = "xml-apis", version.ref = "xmlapisver" }
xmlapisext = { group = "xml-apis", name = "xml-apis-ext", version.ref = "xmlapisextver" }

xmlbeans = { group = "org.apache.xmlbeans", name = "xmlbeans", version.ref = "xmlbeansver" }

xmlresolver = { group = "xml-resolver", name = "xml-resolver", version.ref = "xmlresolverver" }

xmlschemacore = { group = "org.apache.ws.xmlschema", name = "xmlschema-core", version.ref = "xmlschemacorever" }
